# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d855cdd7029b5118384c6c4088a80676d89edc79ba540e01620f9394dd155c2b4de55a8ff339e525af4732de2492987ead37a2a2ef5ed0b15b9f62046f37a0d4

test:
  secret_key_base: 1104f1b72c0abef38f0873f522b0e0ff17302c5a25b513c0d3aa5470ed4cd8c9a17383b078d7dcf684cd2499a677f6410e93945c69abe50d303cd88eebbe8d94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
